main: com.sereneoasis.Serenity
name: Serenity
author: Sakrajin
version: 1.0.0
api-version: '1.20'
depend: [NDatabase]
commands:
  serenity:
    description: Your description
    usage: /<command>
    permission: serenity.command
    aliases: [s, so]