main: com.sereneoasis.SereneAbilities
name: SereneAbilities
author: Sakrajin
version: 1.0.0
api-version: '1.20'
depend: [ NDatabase, WorldGuard ]
commands:
  serenity:
    description: Your description
    usage: /<command>
    permission: serenity.command
    aliases: [ s, so ]